# datasource
spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/hourjob
   username: postgres
   password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
